name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - '*'

jobs:
  mix_test:
    name: mix test (Elixir ${{matrix.elixir}} | Erlang/OTP ${{matrix.otp}})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        elixir: ['1.12', '1.13', '1.14', '1.15', '1.16', '1.17']
        otp: ['24', '25', '26', '27']
        exclude:
          - elixir: '1.12'
            otp: '25'
          - elixir: '1.12'
            otp: '26'
          - elixir: '1.12'
            otp: '27'
          - elixir: '1.13'
            otp: '26'
          - elixir: '1.13'
            otp: '27'
          - elixir: '1.14'
            otp: '27'
          - elixir: '1.15'
            otp: '23'
          - elixir: '1.15'
            otp: '27'
          - elixir: '1.16'
            otp: '23'
          - elixir: '1.16'
            otp: '27'
          - elixir: '1.17'
            otp: '23'
          - elixir: '1.17'
            otp: '24'
        include:
          - elixir: '1.13'
            otp: '25'
            lint: true
          - elixir: '1.14'
            otp: '26'
            lint: true
          - elixir: '1.15'
            otp: '26'
            lint: true
          - elixir: '1.16'
            otp: '26'
            lint: true
          - elixir: '1.17'
            otp: '27'
            lint: true
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
          experimental-otp: true
          version-type: 'loose'
      - name: Install packages
        run: |
          sudo apt-get install -y -qq inotify-tools
      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get --only test
      - run: mix format --check-formatted
        if: matrix.lint
      - run: mix compile --warnings-as-errors
        if: matrix.lint
      - run: mix test
