name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  mix_test:
    name: mix test (Elixir ${{matrix.elixir}} | Erlang/OTP ${{matrix.otp}})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.12.3
            otp: 23.3
          - elixir: 1.12.3
            otp: 24.0
          - elixir: 1.13.4
            otp: 24.0
          - elixir: 1.13.4
            otp: 25.0
            lint: true
          - elixir: 1.14.0
            otp: 25.0
            lint: true
          - elixir: "1.15"
            otp: "26"
            lint: true
          - elixir: "1.16"
            otp: "26"
            lint: true
          - elixir: "1.17"
            otp: "27"
            lint: true
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
          experimental-otp: true
      - name: Install packages
        run: |
          sudo apt-get install -y -qq inotify-tools
      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get --only test
      - run: mix format --check-formatted
        if: matrix.lint
      - run: mix compile --warnings-as-errors
        if: matrix.lint
      - run: mix test
